### ISSUE TITLE
[Enhancement] Caves and Cliffs Noise Based Caves

### ISSUE THREAD

**Issue by Its-Just-Luci** [b3spectacled/modern-beta-fabric#109]
Would it be possible to enable caves and cliffs noise based caves somehow? I think they'd be extremely fun to have in a beta-esque world!

**Comment by Its-Just-Luci** [comment]
found a stopgap solution by stacking dimensions using immersive portals, no longer a personal concern

**Comment by joebig22** [comment]
hey, i've been trying to do that to get the new caves on the beta terrain for a while by stacking the overworld with a random overworld_caves dimension datapack and changing the height values but it keeps having a weird unbreakable block overlap, do you know what I can do to fix it?
or maybe you did it in a different way idk
(flashing lights because of the overlap)
https://github.com/b3spectacled/modern-beta-fabric/assets/138083133/18f87ad3-8495-4697-a757-3563e0e024fa
