### ISSUE TITLE
The mesa biome (badlands) only generate white stained clay and red sand and will not generate at all in some worlds.

### ISSUE THREAD

**Issue by IronLover64** [b3spectacled/modern-beta-fabric#29]
![2021-06-22_16 48 09](https://user-images.githubusercontent.com/51809607/122998079-9a1d1480-d37a-11eb-8d15-fc92d431aa68.png)
![2021-06-22_16 54 53](https://user-images.githubusercontent.com/51809607/122998082-9ab5ab00-d37a-11eb-85fd-a03b049b63fa.png)

**Comment by b3spectacled** [comment]
What is the world type being used here?

EDIT: Can you also provide the versions of Minecraft and the mod being used here?

**Comment by IronLover64** [comment]
1.16.4
beta world type

**Comment by IronLover64** [comment]
Beta world type
Modern biomes
Oceans: yes
Modern Beta mod

**Comment by b3spectacled** [comment]
Thanks, what is the mod version (i.e. v1.0.7, v1.0.8, etc.)?

It looks like you're using an older version of the mod, where this was previously an issue but has since been fixed.  If this is the case, please try [v1.1.1](https://www.curseforge.com/minecraft/mc-mods/modern-beta/files/3282662) (obligatory please make a backup of your world if you have one already).

**Comment by IronLover64** [comment]
Thanks a lot. This isn’t a part of the mod, but how do I reload parts of my world for the new update since the closest mass biome to my spawn has already been generated with the problematic version.

**Comment by b3spectacled** [comment]
You can use [MCASelector](https://github.com/Querz/mcaselector) or some tool like it to open your world save data, delete the unwanted chunks, then regenerate them in-game.
