### ISSUE TITLE
[feature request] Support for negative height terrain generation

### ISSUE THREAD

**Issue by ghost** [b3spectacled/modern-beta-fabric#38]
### Version info

modern-beta-fabric-2.2.1-1.17.1
[gh actions build #22](https://github.com/b3spectacled/modern-beta-fabric/actions/runs/1048068335)
### Expected Behavior

Caves and cliffs preview datapack generates terrain down to y=-64
### Actual Behaviour 
The mod trims caves at y=0 and spams the client with
`[Worker-Main-2/WARN]: Empty height range: [136 absolute-0 below top]`

**Comment by b3spectacled** [comment]
Modern Beta uses its own set of noise settings for the various world types, so I would not expect the CC Preview data pack to work.

Partial support is already in, however I don't advertise it because the work is still pretty incomplete.  However, if you'd still like to try it out, a datapack is attached.  You'll be able to preview the extended height changes for the Beta, Alpha, Infdev 611 and Infdev 415 world types.

I don't plan to address issues until regular 1.18 snapshots start coming out though.

[CavesAndCliffsPreviewModernBeta.zip](https://github.com/b3spectacled/modern-beta-fabric/files/6850699/CavesAndCliffsPreviewModernBeta.zip)
