### ISSUE TITLE
Safe to move to a Vanilla server?

### ISSUE THREAD

**Issue by NinCollin** [b3spectacled/modern-beta-fabric#53]
I'm currently using this mod to generate an assortment of different versions of chunks with the intention of loading them in a Vanilla server, however, a slew of warnings are thrown upon doing so.
I've got the biome generation set to 'vanilla' so the chunks themselves should be fine; however, I'm wondering if this mod using custom structure names (like for the ocean shrines) will adversely affect something somehow.

**Comment by b3spectacled** [comment]
Yes, the modded structure references are likely the issue here. You can try using this tool to remove all references to modded structures in every chunk you're trying to import: https://github.com/Nyveon/MCStructureCleaner. Please be sure to back up your world before running this tool, as it appears 1.18 worlds may not be fully supported.

**Comment by NinCollin** [comment]
Ooooo thanks a bunch! This seems to be what I was looking for. I've been using 1.17.1 just in case anyways to avoid any potential compatibility issues with 1.18, so I should be good. Thanks again!
