### ISSUE TITLE
Modern Beta doesn't work on 1.18.2

### ISSUE THREAD

**Issue by Zockerhopper** [b3spectacled/modern-beta-fabric#56]
It seems that all of the Bippity Boppity World Generation and Feature placement magic has somehow broken this Mod since when I try to run this with the most up to date Fabric 0.13.3 and Fabric API 0.48.0 it just tells me:"This crash may be caused by an invalid Java Runtime configuration. Check any custom configuration settings." Without even giving me a crash log. This proves that they should add these sorts of changes for new major Updates and not in the middle of the old update.

**Comment by Nolij** [comment]
Tried to see if I could update this. There have been significant changes to internal world gen code. There were several errors caused by attempting to build for 1.18.2. There will likely need to be some very big changes to the mod, and the author is probably the only person with the familiarity with it necessary to do that.

I wouldn't be surprised if they've already started updating but its just taking a while due to all the internal changes.

**Comment by b3spectacled** [comment]
Yes, my free time is a lot more limited these days, but the update is in progress. The world gen changes are indeed very significant, so I'll be working through the snapshots up to 1.18.2 to make sure I can manage it.

**Comment by Nolij** [comment]
> Yes, my free time is a lot more limited these days, but the update is in progress. The world gen changes are indeed very significant, so I'll be working through the snapshots up to 1.18.2 to make sure I can manage it.

If there's any parts you can give some basic instructions for that I can help with (assuming it's not more effort to tell me how to do it than to do it yourself) feel free to hit me up. Discord is xdMatthewbx#1337

**Comment by b3spectacled** [comment]
Unfortunately, I've spent some time on working on the update and arrived at an impasse. The 1.18.2 world gen changes are above and beyond anything Mojang have done; so, I'm going to put the update on hold for now. I understand the reason for the changes, complete control of the noise sampling used for world generation. But I don't get the point when the noise settings are now beyond convoluted, to the point that I wonder if the intended end user (random players) could even make sense of the .json worldgen files.

I'm going to shift my focus to addressing the issues that affect the current 1.18.1 version. I apologize and appreciate the support.

EDIT: All this said, most of the actual classic world generation code is an independent re-implementation. The stuff that has changed in vanilla has to do with the new noise cave and aquifer generation which said classic world gen code interfaced with. One option could be to just strip all of that out for the time being, but this is something I'm pretty reluctant to do.

**Comment by vrgtics** [comment]
hey, I'm kind of naughty, because someone somewhere taught me similar-
method to download the "testing/dev version" at few moments ago. I'm 
Sorry for moderators. I'm going to peak this mod for 1.18.2, 

_**please remember this is still beta, devs is still fixing some problems,
meaning may cause some issue in this mod. In my case, it works perfectly fine:**_
_disclaimer: me using windows 10_

1) go here: https://github.com/b3spectacled/modern-beta-fabric/actions/runs/2178226759
2) **scroll down** as you can see there are **The only Single Package**, call _`'build-artifacts'` a `.zip` file_
3) **click and download** _the package_ _(I just noticed that you **Only Login after** can appear embed "blue text" to download `'build-artifacts'` `.zip` file)_
4) once you got _the package_ then **Extract the _`.zip` file_**
inside `'build-artifacts'` `.zip`, you can see _4 Different `.jar`_, 
5) **You MUST pick** `modern-beta-fabric-3.0.3+1.18.2.jar`  _{cut 'ctrl+x'} to the Minecraft `'mods'` folder..}_
**(named include`-dev`,`-sources`,`-sources-dev` Is NOT What You Looking For)**
installing `.jar` regular method once again **_(_open with_ winRAR archiver might coming-
handy, use your mouse pull straight out)_**

**_`Good luck for installing! Congratulations if you successfully installed!!`_**
**_`I wish this method of installation if still isn't officially publish in future could also be help.`_**

Have a nice day :)

**Comment by Nolij** [comment]
Regarding above: not a full release! I think I speak for the dev when I say use the above in worlds you value at your own risk! It is being developed by this developer and is legitimate but it is an early version and if it were ready for a full release it would be one. Do not blame anyone but yourself if the above beta version breaks your world!

**Comment by b3spectacled** [comment]
Updated for 1.18.2, finally! Thanks for your support!
