### ISSUE TITLE
Mushroom Islands added to Voronoi points list doesn't generate Mycelium

### ISSUE THREAD

**Issue by Pokepunch** [b3spectacled/modern-beta-fabric#83]
I wanted to add more of the vanilla biomes to the Voronoi points list, so as a test I added mushroom_fields and removed every other biome to see if it would generate. The world generated but the Mycelium didn't and instead was replaced with Grass. 

I tried to test it without removing all the other entries in the list but have been unable to find a Mushroom Island using the locate command as it freezes the game each time (Although I think this part is caused by a current vanilla issue https://bugs.mojang.com/browse/MC-250276)

Could you advise if this is a bug or intentional? I know you don't plan to support Vanilla biome options but it still seems like a bug for the Voronoi option that seems to be the replacement for it.

**Comment by b3spectacled** [comment]
Thanks, I'll look into this.

**Comment by b3spectacled** [comment]
Also wanted to add, I am aware of the game hanging when locating biomes, this is unfortunately due to how the ocean and cave biomes are injected in a post-processing step. The game hasn't crashed or completely frozen though, it just needs extra time to complete the search.

That said, this wasn't documented as a known issue so I just did that. Thanks for pointing it out.

**Comment by b3spectacled** [comment]
Please take a look at 6.2+1.19.4, which should fix this issue. 6.2 also adds a 'Beta Vanilla' world preset option, which generates Mushroom Fields biomes (among most other vanilla biomes).
